// Automatically generated by scripts/compile-plugin-zip.ts
export interface ZipPackageMetadata {
  fileName: string;
  filePath: string;
  fileSizeBytes: number;
  fileSizeFormatted: string;
  totalFiles: number;
  sha256: string;
  md5: string;
  compiledAt: string;
}

export const COMPILED_ZIP_METADATA: ZipPackageMetadata = {
  "fileName": "faiiya-pay.zip",
  "filePath": "/faiiya-pay.zip",
  "fileSizeBytes": 44112,
  "fileSizeFormatted": "43.1 KB",
  "totalFiles": 22,
  "sha256": "f7d1673108cb88cfab92a128d605641bb512416ebefcb7e301322941de10f9b6",
  "md5": "3390c6f032ba049eae86e43c7db973ab",
  "compiledAt": "2026-09-30T14:43:51.394Z"
};
