import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import JSZip from 'jszip';
import { PLUGIN_FILES } from '../src/services/pluginFiles';

async function compilePluginZip() {
  console.log('📦 Starting Faiiya Pay WordPress Plugin ZIP compilation...');

  const publicDir = path.resolve(process.cwd(), 'public');
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const zipPath = path.join(publicDir, 'faiiya-pay.zip');

  // STEP 1: Delete previous zip file in public if it exists
  if (fs.existsSync(zipPath)) {
    console.log('🗑️  Deleting previous public/faiiya-pay.zip to guarantee clean replacement...');
    fs.unlinkSync(zipPath);
  }

  // STEP 2: Clean plugin-source directory
  const pluginSourceDir = path.resolve(process.cwd(), 'plugin-source/faiiya-pay');
  if (fs.existsSync(pluginSourceDir)) {
    fs.rmSync(pluginSourceDir, { recursive: true, force: true });
  }
  fs.mkdirSync(pluginSourceDir, { recursive: true });

  // STEP 3: Build ZIP structure from current PLUGIN_FILES
  const zip = new JSZip();
  const rootFolder = zip.folder('faiiya-pay');

  if (!rootFolder) {
    throw new Error('Failed to create root folder in zip');
  }

  for (const file of PLUGIN_FILES) {
    // Add to zip
    rootFolder.file(file.path, file.content, {
      date: new Date('2026-09-30T12:00:00Z'),
      unixPermissions: '644',
    });

    // Write to disk in plugin-source for inspection
    const destPath = path.join(pluginSourceDir, file.path);
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    fs.writeFileSync(destPath, file.content, 'utf8');
  }

  // STEP 4: Generate nodebuffer with max DEFLATE compression
  const buffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });

  // STEP 5: Write new zip file to public
  fs.writeFileSync(zipPath, buffer);

  // STEP 6: Integrity Verification - Read back and verify all files
  const verifyZip = new JSZip();
  const loadedZip = await verifyZip.loadAsync(buffer);
  const zipFileCount = Object.keys(loadedZip.files).filter((k) => !loadedZip.files[k].dir).length;

  if (zipFileCount !== PLUGIN_FILES.length) {
    throw new Error(
      `ZIP verification failed! Expected ${PLUGIN_FILES.length} files, but ZIP contains ${zipFileCount} files.`
    );
  }

  const stats = fs.statSync(zipPath);
  const sha256 = crypto.createHash('sha256').update(buffer).digest('hex');
  const md5 = crypto.createHash('md5').update(buffer).digest('hex');

  const metadata = {
    fileName: 'faiiya-pay.zip',
    filePath: '/faiiya-pay.zip',
    fileSizeBytes: stats.size,
    fileSizeFormatted: (stats.size / 1024).toFixed(1) + ' KB',
    totalFiles: PLUGIN_FILES.length,
    sha256,
    md5,
    compiledAt: new Date().toISOString(),
  };

  const metadataPath = path.resolve(process.cwd(), 'src/services/zipMetadata.ts');
  const metadataContent = `// Automatically generated by scripts/compile-plugin-zip.ts
export interface ZipPackageMetadata {
  fileName: string;
  filePath: string;
  fileSizeBytes: number;
  fileSizeFormatted: string;
  totalFiles: number;
  sha256: string;
  md5: string;
  compiledAt: string;
}

export const COMPILED_ZIP_METADATA: ZipPackageMetadata = ${JSON.stringify(metadata, null, 2)};
`;

  fs.writeFileSync(metadataPath, metadataContent, 'utf8');

  console.log(`✅ Successfully replaced public/${metadata.fileName}!`);
  console.log(`   Path: public/faiiya-pay.zip`);
  console.log(`   Size: ${metadata.fileSizeFormatted} (${metadata.fileSizeBytes} bytes)`);
  console.log(`   Verified files: ${zipFileCount} production plugin files in root folder /faiiya-pay`);
  console.log(`   SHA-256: ${sha256}`);
}

compilePluginZip().catch((err) => {
  console.error('❌ Error compiling plugin zip:', err);
  process.exit(1);
});
